src/org/sosy_lab/solver/mathsat5/Mathsat5FormulaManager.java
src/org/sosy_lab/solver/mathsat5/Mathsat5TheoremProver.java

MathSat5 has the possibility to interrupt AllSAT queries. This set of changes adds support for this feature in JavaSMT.

Mathsat5: Support of interrupting AllSAT calls.

---

src/org/sosy_lab/java_smt/solvers/z3/Z3SolverContext.java

Previously model generation was always turned on, and unsat-core generation never.
I wonder why unsat-core generation seems to succeed anyway (the [default is false](https://github.com/Z3Prover/z3/blob/e8f4dd76c21b52460b6bd95487183aea88749ce0/src/cmd_context/context_params.cpp#L169)), so I would like to have your opinion on this.

Enable model and unsat-core generation in Z3 only for solver instances where we need it.

---

README.md
doc/javadoc_overview.html

The example in the README uses the old package name, `org.sosy_lab.solver`, but in the current version the root package is now `org.sosy_lab.java_smt`; this commit updates the example to use the correct package.

Update package name in README examples and Javadoc overview

---

src/org/sosy_lab/java_smt/solvers/mathsat5/Mathsat5TheoremProver.java

If instantiating a Mathsat5TheoremProver to generate unsat cores, automatically set the option to switch off the eager BV interface to fix issue #113.

Fix issue #113

---

src/org/sosy_lab/java_smt/solvers/smtinterpol/SmtInterpolEnvironment.java
src/org/sosy_lab/java_smt/solvers/smtinterpol/SmtInterpolFormulaManager.java

This PR contains changes required by CPAchecker for updating the LassoRanker library that strongly depends on SMTInterpol and requires direct access to its components.

CPAchecker LassoRanker Update

---

.appveyor.yml

The upload of JUnit-tests is limited by 30.000 (plus some overhead).
Since several months we got timeouts or strange errors from the upload step.
Now we ignore a large subset of JUnit-tests in the upload-step (the tests are executed!) to stay under the limitation.

Appvoyer-CI has an internal limitation for unit-test-upload.

---

src/org/sosy_lab/java_smt/test/SolverConcurrencyTest.java

This branch is by no means done!
I just wanted a first impression of @kfriedberger concerning the complexity and because i break with our test paradigm quite a bit.
Main idea is to test SolverContext concurrency with pre-made contexts (each thread gets a single unique context that exists to work concurrenlty), each thread creating its own SolverContext and work concurrently, test parallel optimization (we need to recompile OptimathSAT for that) and test parallel stack usage in a single context.
The main reason for not using `SolverBasedTest0` is that control of the creation and closing of SolverContexts is needed.
Methods `initSolver `and `closeSolver`.
I tried to start the threads of a test as synchronous as possible and wait for all of them to finish before continuing, providing maximum …

Concurrency tests

---

build/build-maven-publish.xml
doc/Developers-How-to-Release-into-Ivy.md
doc/Developers-How-to-Release-into-Maven.md
doc/Developers.md
doc/Example-Maven-Project/pom.xml
doc/Example-Maven-Web-Project/pom.xml
lib/ivy.xml
solvers_maven_conf/maven_javasmt_yices2_pom.xml
solvers_maven_conf/maven_yices2_pom.xml

This PR simplifies the process of releasing into Maven repository.
We update the corresponding documentation.
And we take a look at releasing Yices2 to Maven (#221), too, as this is still missing for JavaSMT.

Improve the process of releasing into Maven repository

---

docker/buildUbuntu1804.sh
docker/runUbuntu1804.sh
docker/ubuntu1804.Dockerfile
lib/ivy.xml

The Docker image is based on Ubuntu 18.04, with additional software for building Boolector and other solver binaries.
Boolector was then updated to its latest version 3.2.2 from the Git repository.

Update Boolector to version 3.2.2 with a build process via a new Docker image

---

src/org/sosy_lab/java_smt/api/StringFormulaManager.java
src/org/sosy_lab/java_smt/basicimpl/AbstractStringFormulaManager.java
src/org/sosy_lab/java_smt/delegate/statistics/StatisticsStringFormulaManager.java
src/org/sosy_lab/java_smt/delegate/synchronize/SynchronizedStringFormulaManager.java
src/org/sosy_lab/java_smt/solvers/cvc4/CVC4StringFormulaManager.java
src/org/sosy_lab/java_smt/solvers/z3/Z3StringFormulaManager.java
src/org/sosy_lab/java_smt/test/StringFormulaManagerTest.java

This function corresponds to `re.allchar` in http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml. It is implemented by the Z3 and CVC4 solvers. It was previously removed by mistake. Fixes #281.
Running tests with `ant tests` (before or after applying these changes) yields test errors. CVC4 tests all fail and some Z3 tests fail. For Z3 tests, this does not happen when they are run individually. I am unsure if this is expected or if I should change the way I run tests. However, the newly added test case passes with Z3.

Add allChar function, fix #281

---

src/org/sosy_lab/java_smt/basicimpl/AbstractStringFormulaManager.java
src/org/sosy_lab/java_smt/test/StringFormulaManagerTest.java

While working with the theory of strings, I saw unexpected behavior when using regex intersection or difference. It turns out that union was used for those operations instead of intersection. I made the correction and added 3 unit tests. I also made a fix to `testRegexAllCharUnicode()`, which was only passing because of this bug.

Fix bug in regex intersection and difference

---

src/org/sosy_lab/java_smt/api/Evaluator.java
src/org/sosy_lab/java_smt/api/FloatingPointNumber.java
src/org/sosy_lab/java_smt/api/FormulaType.java
src/org/sosy_lab/java_smt/basicimpl/AbstractEvaluator.java
src/org/sosy_lab/java_smt/basicimpl/CachingModel.java
src/org/sosy_lab/java_smt/delegate/statistics/StatisticsModel.java
src/org/sosy_lab/java_smt/delegate/synchronize/SynchronizedModel.java
src/org/sosy_lab/java_smt/delegate/synchronize/SynchronizedModelWithContext.java
src/org/sosy_lab/java_smt/solvers/cvc4/CVC4FormulaCreator.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5FormulaCreator.java
src/org/sosy_lab/java_smt/solvers/mathsat5/Mathsat5FormulaCreator.java
src/org/sosy_lab/java_smt/solvers/yices2/Yices2Model.java
src/org/sosy_lab/java_smt/solvers/yices2/Yices2NativeApiTest.java
src/org/sosy_lab/java_smt/solvers/z3/Z3FormulaCreator.java
src/org/sosy_lab/java_smt/test/FloatingPointFormulaManagerTest.java
src/org/sosy_lab/java_smt/test/FloatingPointNumberTest.java
src/org/sosy_lab/java_smt/test/ModelTest.java

see #352 for details.
Our implementation should work for arbitrary bit-sizes of floating-point numbers.
However, Z3 does not support the extraction of bits from NaN, so the implementation is is potentially unsound for NaN-based formulas.

352 add model evaluation on FloatingPointFormula

---

src/org/sosy_lab/java_smt/api/FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/basicimpl/AbstractFloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/delegate/statistics/StatisticsFloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/delegate/synchronize/SynchronizedFloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/solvers/cvc4/CVC4FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/solvers/mathsat5/Mathsat5FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/solvers/z3/Z3FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/test/FloatingPointFormulaManagerTest.java

As discussed in https://github.com/sosy-lab/java-smt/issues/360, this PR adds the fp.rem operation in the floatingpoint formula manager.
I also added some light tests, as to prove that the operation behaves as expected. Let me know if I should add more.

Add fp.rem operation to FloatingPointFormulaManager

---

src/org/sosy_lab/java_smt/api/FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/basicimpl/AbstractFloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/delegate/statistics/StatisticsFloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/delegate/synchronize/SynchronizedFloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/solvers/cvc4/CVC4FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/solvers/mathsat5/Mathsat5FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/solvers/z3/Z3FloatingPointFormulaManager.java
src/org/sosy_lab/java_smt/test/FloatingPointFormulaManagerTest.java

As discussed in #360, currently, floating point literals cannot be directly created if the user has access to the bit pattern of the value. Therefore, this PR adds support for this using the new `makeNumber(BigInteger exponent, BigInteger mantissa, boolean signBit, FloatingPointType type)` method.
I added a test to verify that no trivial mistakes were made. Let me know if I should add more.

Add new floating point literal constructor using IEEE754 bitpattern

---

docker/buildUbuntu1804.sh
lib/ivy.xml
lib/native/source/opensmt/api.patch
lib/native/source/opensmt/swig/opensmt/InterpolationContext.i
lib/native/source/opensmt/swig/opensmt/MainSolver.i
src/org/sosy_lab/java_smt/solvers/opensmt/OpenSmtAbstractProver.java
src/org/sosy_lab/java_smt/solvers/opensmt/OpenSmtInterpolatingProver.java
src/org/sosy_lab/java_smt/solvers/opensmt/OpenSmtNativeAPITest.java
src/org/sosy_lab/java_smt/solvers/opensmt/OpenSmtTheoremProver.java
src/org/sosy_lab/java_smt/test/BooleanFormulaSubjectTest.java
src/org/sosy_lab/java_smt/test/ProverEnvironmentSubjectTest.java
src/org/sosy_lab/java_smt/test/ProverEnvironmentTest.java
src/org/sosy_lab/java_smt/test/SolverBasedTest0.java

Hello,
this pull request adds support for the new method MainSolver.getUnsatCore() to our JavaSMT backend for OpenSMT. The feature is still experimental in OpenSMT and so far only the logics QF_UF, QF_LIA and QF_LRA are supported. More details can be found [here](https://github.com/usi-verification-and-security/opensmt/issues/619).

Add support for UNSAT core to the OpenSMT backend

---

src/org/sosy_lab/java_smt/basicimpl/AbstractProver.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5AbstractProver.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5InterpolatingProver.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5TheoremProver.java
src/org/sosy_lab/java_smt/test/InterpolatingProverTest.java

#381 improve interpolation behaviour

---

src/org/sosy_lab/java_smt/api/FunctionDeclarationKind.java
src/org/sosy_lab/java_smt/solvers/bitwuzla/BitwuzlaFloatingPointManager.java
src/org/sosy_lab/java_smt/solvers/bitwuzla/BitwuzlaFormulaCreator.java
src/org/sosy_lab/java_smt/solvers/bitwuzla/BitwuzlaFormulaManager.java
src/org/sosy_lab/java_smt/solvers/bitwuzla/BitwuzlaTheoremProver.java
src/org/sosy_lab/java_smt/solvers/cvc4/CVC4FormulaCreator.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5FormulaCreator.java
src/org/sosy_lab/java_smt/solvers/z3/Z3FormulaCreator.java
src/org/sosy_lab/java_smt/test/FloatingPointFormulaManagerTest.java

Hello,
this MR aims to fix the performance issues described in #371. The problem was not about the conversion operation itself, but about the large number of ProverEnvironments that would be created, one for each test input. We solve this by reusing the same ProverEnvironment for all inputs of the test. This also improves the performance of Z3 for those same tests.
In addition to that the MR includes a number of minor fixes:
- Bitwuzla does not support float-to-bitvector conversions and we are using a work-around that introduces new side-conditions for the casts. We now make sure that side-conditions are only pushed onto the stack when needed. The old version would simply include everything in the query, even for variables that don't occur in the assertions, which can cause significant …

Bitwuzla: Fix performance issues in FloatingPointFormulaManagerTest

---

doc/Getting-started.md

Note the org name here
`https://mvnrepository.com/artifact/org.sosy-lab`
Otherwise perhaps I can add a note to use different org names depending on mvn vs sosy-lab repo usage?
Also bumps version to 5.0.1

Fix ivy dependency org name

---

docker/buildUbuntu1804.sh
docker/buildUbuntu2204.sh
docker/runUbuntu1804.sh
docker/runUbuntu2204.sh
docker/ubuntu1804.Dockerfile
docker/ubuntu2204.Dockerfile

Hello,
as reported in #414 the docker build images are no longer working with the latest Ubuntu release. There seems to be an issue with the work-around we use to build the solver binaries as a user inside the Docker image. I've tried finding a solution, but had no luck so far. This pull request now aims to replace Docker with Podman entirely.
Podman is a drop in replacement for Docker and supports the same command line options, making larger changes to our build scripts unnecessary. It also runs in user mode by default, meaning that we no longer need the work around that is broken now.

Use Podman for the build container

---

lib/native/source/get_jni_headers.sh
lib/native/source/libmathsat5j/compile.sh

The produced library can _not_ be distributed yet, because the script does not sign it.

Extend compile.sh for libmathsat5j for macOS dylib

---

src/org/sosy_lab/java_smt/api/BitvectorFormulaManager.java
src/org/sosy_lab/java_smt/api/FloatingPointFormulaManager.java

I do not see any benefit for JavaSMT and do not like  the idea of re-adding old stuff.
The group of users, mostly developers of related projects, are maybe never using this code and might never compare older JavaSMT versions with a newer one.
Nevertheless, the PR is here.

add deprecated methods for maybe binary compatibility

---

src/org/sosy_lab/java_smt/test/TimeoutTest.java

Bitwuzla has a flaky timeout test on Windows. This PR tweaks some parameters to improve the test behavior.
See #435 for details.

Tweak TimeoutTest Parameters due to Bitwuzla Windows Flaky Test

---

lib/native/arm64-linux/libopensmtjava.so
lib/native/arm64-windows/README.md
lib/native/x86_64-windows/README.md

Hello,
I've noticed that there is a broken symlink in `lib/native/arm64-linux`. The README file for `lib/native/x86-64-windows` is also outdated, and we're missing instructions to link the binaries for windows on arm64. This PR should take care of all these minor issues.

Fix library symlinks

---

src/org/sosy_lab/java_smt/test/StringFormulaManagerTest.java

A Z3 regression in a String test is resolved by reordering the formulas subexpressions (without changing them).
I added a TODO so that we can take a look at this with a new Z3 version. I also suggest to not close the issue until then.
See #439 for more info.

Reorder test formula in testStringVariableReplaceSubstring() to fix Z3 regression

---

src/org/sosy_lab/java_smt/api/StringFormulaManager.java
src/org/sosy_lab/java_smt/solvers/cvc4/CVC4StringFormulaManager.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5StringFormulaManager.java
src/org/sosy_lab/java_smt/solvers/princess/PrincessEnvironment.java
src/org/sosy_lab/java_smt/solvers/princess/PrincessStringFormulaManager.java
src/org/sosy_lab/java_smt/test/StringFormulaManagerTest.java

Hello,
I've noticed that there is a precondition the `char` override for `StringFormulaManager.range`:
```
* @return formula denoting the range regular expression over two chars.
* @see #range(StringFormula, StringFormula)
*/
default RegexFormula range(char start, char end) {
Preconditions.checkArgument(
start <= end,
"Range from start '%s' (%s) to end '%s' (%s) is empty.",
start,
(int) start,
end,
(int) end);
return range(makeString(String.valueOf(start)), makeString(String.valueOf(end)));
}
```
However, the JavaDoc for the (general) `range` method does not mention this restriction:
```
/**
* @return formula denoting the range regular expression over two sequences of length 1.
*/
RegexFormula range(StringFormula start, StringFormula end);
```
And, according to SMTLIB, empty ranges should …

Allow empty String ranges

---

src/org/sosy_lab/java_smt/solvers/z3/Z3NumeralFormulaManager.java
src/org/sosy_lab/java_smt/test/NumeralFormulaManagerTest.java

Hello,
Z3 crashes when `NumeralFormulaManager.sum()` is called with no arguments. This PR adds some checks to handle this special-case.

Fix empty sums in Z3

---

src/org/sosy_lab/java_smt/solvers/cvc4/CVC4NumeralFormulaManager.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5NumeralFormulaManager.java
src/org/sosy_lab/java_smt/solvers/smtinterpol/SmtInterpolNumeralFormulaManager.java
src/org/sosy_lab/java_smt/solvers/yices2/Yices2NumeralFormulaManager.java
src/org/sosy_lab/java_smt/test/NumeralFormulaManagerTest.java

Hello,
several solvers crash when `NumeralFormulaManager.distinct()` is used with fewer than 2 arguments. This PR adds support for such special-cases to all solvers.

Add special-case handling for distinct() with fewer than 2 arguments

---

src/org/sosy_lab/java_smt/solvers/mathsat5/Mathsat5IntegerFormulaManager.java
src/org/sosy_lab/java_smt/test/NonLinearArithmeticWithModuloTest.java
src/org/sosy_lab/java_smt/test/NumeralFormulaManagerTest.java
src/org/sosy_lab/java_smt/test/SolverTheoriesTest.java

Hello,
MathSAT is missing native support for integer modulo. In this PR we add a work-around based on the definition `remainder = dividend - floor(dividend/divisor)*divisor` to support the operation.

Add support for integer modulo in MathSAT

---

lib/ivy.xml
lib/native/source/libmathsat5j/includes/defines.h
lib/native/source/libmathsat5j/org_sosy_1lab_java_1smt_solvers_mathsat5_Mathsat5NativeApi.c
src/org/sosy_lab/java_smt/solvers/mathsat5/Mathsat5NativeApi.java
src/org/sosy_lab/java_smt/solvers/mathsat5/Mathsat5NativeApiTest.java

This PR extends the Mathsat5 wrapper with API for proofs and adds a small native test for them.
Unfortunately this came up after the merge of the most recent changes. Sorry about that.

Extend Mathsat5 Native Wrapper with API for Proofs

---

src/org/sosy_lab/java_smt/test/SolverConcurrencyTest.java
src/org/sosy_lab/java_smt/test/TimeoutTest.java

Hello,
the flaky tests seem to have gotten worse after the recent update to CVC5. I would suggest disabling `TimoutTest` and `SolverConcurrencyTest` entirely for CVC5 to temporarily fix the issue. The concurrency issues with CVC5 are well known and have already been reported [here](https://github.com/cvc5/cvc5/issues/10256) and [here](https://github.com/cvc5/cvc5/discussions/10265). They seem to be working on a solution, but it will take more time. In the meantime we should have a test-suite that is always green, and once the concurrency problems in CVC5 are resolved the test can easily be turned on again.

Disable the flaky tests for CVC5

---

build.xml
build/build-publish-solvers/solver-opensmt.xml
doc/Developers-How-to-Release-into-Ivy.md
docker/buildUbuntu1804.sh
docker/buildUbuntu2204.sh
docker/runUbuntu1804.sh
docker/runUbuntu2204.sh
docker/ubuntu1804.Dockerfile
docker/ubuntu2204.Dockerfile
lib/ivy.xml
lib/native/source/opensmt/api.patch
lib/native/source/opensmt/opensmt-wrap.cpp
lib/native/source/opensmt/src/org/sosy_lab/java_smt/solvers/opensmt/api/MainSolver.java
lib/native/source/opensmt/src/org/sosy_lab/java_smt/solvers/opensmt/api/OsmtNativeJNI.java
lib/native/source/opensmt/swig/opensmt/ArithLogic.i
lib/native/source/opensmt/swig/opensmt/Logic.i
lib/native/source/opensmt/swig/opensmt/MainSolver.i
src/org/sosy_lab/java_smt/solvers/opensmt/OpenSmtNativeAPITest.java

Hello everyone,
this PR will update OpenSMT to version 2.9.0 while also adding the method `MainSolver.printResolutionProofSMT2` to the JNI bindings in preparation for https://github.com/sosy-lab/java-smt/pull/458. There are also some minor simplifications to the build process and the binaries for GMP on x86-linux and arm64-linux are now included in the build container and no longer have to be provided by the maintainer when updating the binaries.

Update OpenSMT to 2.9.0 and include support for proofs in the JNI bindings

---

lib/ivy.xml
src/org/sosy_lab/java_smt/delegate/debugging/DebuggingSolverInformation.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5NativeAPITest.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5SolverContext.java
src/org/sosy_lab/java_smt/test/DebugModeTest.java
src/org/sosy_lab/java_smt/test/SolverConcurrencyTest.java
src/org/sosy_lab/java_smt/test/SolverThreadLocalityTest.java
src/org/sosy_lab/java_smt/test/TimeoutTest.java

Hello everyone,
the CVC5 developers now seem to have fixed their concurrency issues, and all references to the thread-local NodeManager have now been removed, see [here](https://github.com/cvc5/cvc5/pull/11816). They have also implemented a fix for a separate race condition in the JNI bindings that was reported by us [here](https://github.com/cvc5/cvc5/issues/10256). This means we should now be able to pass CVC5 terms and solver instances from one thread to another without running into any issues.
In this PR we updates the binaries to the latest daily release that includes the fixes. This will close #310 and #347. Issue #469 may also be fixed by it, but we should look at this separately.

Update CVC5 to fix the concurrency issues

---

src/org/sosy_lab/java_smt/api/visitors/BooleanFormulaTransformationVisitor.java
src/org/sosy_lab/java_smt/api/visitors/BooleanFormulaVisitor.java
src/org/sosy_lab/java_smt/api/visitors/DefaultBooleanFormulaVisitor.java
src/org/sosy_lab/java_smt/api/visitors/DefaultFormulaVisitor.java
src/org/sosy_lab/java_smt/api/visitors/FormulaTransformationVisitor.java
src/org/sosy_lab/java_smt/api/visitors/FormulaVisitor.java
src/org/sosy_lab/java_smt/basicimpl/AbstractBooleanFormulaManager.java
src/org/sosy_lab/java_smt/basicimpl/AbstractQuantifiedFormulaManager.java
src/org/sosy_lab/java_smt/basicimpl/FormulaTransformationVisitorImpl.java
src/org/sosy_lab/java_smt/basicimpl/RecursiveFormulaVisitorImpl.java
src/org/sosy_lab/java_smt/basicimpl/Tokenizer.java
src/org/sosy_lab/java_smt/example/FormulaClassifier.java
src/org/sosy_lab/java_smt/solvers/bitwuzla/BitwuzlaFormulaCreator.java
src/org/sosy_lab/java_smt/solvers/boolector/BoolectorFormulaCreator.java
src/org/sosy_lab/java_smt/solvers/cvc4/CVC4FormulaCreator.java
src/org/sosy_lab/java_smt/solvers/cvc4/CVC4QuantifiedFormulaManager.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5FormulaCreator.java
src/org/sosy_lab/java_smt/solvers/cvc5/CVC5QuantifiedFormulaManager.java
src/org/sosy_lab/java_smt/solvers/princess/PrincessFormulaCreator.java
src/org/sosy_lab/java_smt/solvers/princess/PrincessQuantifiedFormulaManager.java
src/org/sosy_lab/java_smt/solvers/yices2/Yices2FormulaCreator.java
src/org/sosy_lab/java_smt/solvers/z3/Z3FormulaCreator.java
src/org/sosy_lab/java_smt/solvers/z3/Z3QuantifiedFormulaManager.java
src/org/sosy_lab/java_smt/test/FormulaClassifierTest.java
src/org/sosy_lab/java_smt/test/SolverTacticsTest.java

The usage of bound variables and quantifier usage in the API was never consistent:
- some solvers require bound variables in quantified formulas, some solvers just use regular variables.
- some solvers visit bound variables in formulas, some solvers just handle them as regular variables.
- some solvers can not use an empty list of variables in quantification, Princess does allow this.
This PR unifies the beaviour and marks the corresponding methods as deprecated:
- all solvers provide only free variables toward the API/user
- all sub-formulas are consistent when visiting quantified formulas, e.g. the body of a quantified formula is provided in a bound-free way, e.g, all bound variables are replaced by free counterparts (for Princess, we use a new temporary unique name, other solvers keep …

Cleanup usage of bound variables

---

lib/ivy.xml
src/org/sosy_lab/java_smt/basicimpl/AbstractBitvectorFormulaManager.java
src/org/sosy_lab/java_smt/test/BitvectorFormulaManagerTest.java
src/org/sosy_lab/java_smt/test/RotationVisitorTest.java

see https://github.com/sosy-lab/java-smt/issues/493

Z3/version update from 4.14.0 to 4.15.2
